print("=================================")
print("          MY PROFILE             ")
print("=================================")
print("Name       : Dhruv Yadav")
print("Age        : 18")
print("Course     : B.Sc.CS")
print("College    : MVLU College ")
print("City       : Mumbai")
print("Skills     : Python, AI promting, C++")
print("===============END==================")
